server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_DIALECT}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console

app:
  frontend-url: ${FRONTEND_URL}
  base-url: ${BASE_URL}
  mail:
    api-url: ${MAIL_API_URL:https://api.brevo.com/v3/smtp/email}
    api-key: ${MAIL_API_KEY}
    from-address: ${MAIL_FROM}
    from-name: ${MAIL_FROM_NAME:LinkLite}
    request-timeout-ms: ${MAIL_REQUEST_TIMEOUT_MS:5000}

  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: ${JWT_EXPIRATION_MS}
  otp-expiration-minutes: ${OTP_EXPIRATION_MINUTES}
  dev-print-otp: ${DEV_PRINT_OTP:false}
  seed-demo-data: ${SEED_DEMO_DATA:false}

  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    first-name: ${ADMIN_FIRST_NAME}
    last-name: ${ADMIN_LAST_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health
